/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEtchMarket,
  IEtchMarketInterface,
} from "../../../contracts/EtchMarketSweep.sol/IEtchMarket";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "ethscriptionId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "quantity",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "startTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "protocolFeeDiscounted",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "creatorFee",
            type: "uint16",
          },
          {
            internalType: "bytes",
            name: "params",
            type: "bytes",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct OrderTypes.EthscriptionOrder",
        name: "order",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "trustedSign",
        type: "bytes",
      },
    ],
    name: "executeEthscriptionOrder",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "bytes32[]",
            name: "ethscriptionIds",
            type: "bytes32[]",
          },
          {
            internalType: "uint256[]",
            name: "quantities",
            type: "uint256[]",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "startTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "protocolFeeDiscounted",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "creatorFee",
            type: "uint16",
          },
          {
            internalType: "bytes",
            name: "params",
            type: "bytes",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct BatchOrder.EthscriptionOrder",
        name: "order",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "value",
                type: "bytes32",
              },
              {
                internalType: "enum BatchOrder.MerkleTreeNodePosition",
                name: "position",
                type: "uint8",
              },
            ],
            internalType: "struct BatchOrder.MerkleTreeNode[]",
            name: "proof",
            type: "tuple[]",
          },
        ],
        internalType: "struct BatchOrder.MerkleTree",
        name: "merkleTree",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "executeOrderWithMerkle",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IEtchMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IEtchMarketInterface {
    return new utils.Interface(_abi) as IEtchMarketInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtchMarket {
    return new Contract(address, _abi, signerOrProvider) as IEtchMarket;
  }
}
