/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEtchMarket,
  IEtchMarketInterface,
} from "../../../contracts/interfaces/IEtchMarket";

const _abi = [
  {
    inputs: [],
    name: "CurrencyInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "ETHTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "EmptyOrderCancelList",
    type: "error",
  },
  {
    inputs: [],
    name: "EthscriptionInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "ExpiredSignature",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientConfirmations",
    type: "error",
  },
  {
    inputs: [],
    name: "MerkleProofInvalid",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "MerkleProofTooLarge",
    type: "error",
  },
  {
    inputs: [],
    name: "MsgValueInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "NoncesInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderNonceTooLow",
    type: "error",
  },
  {
    inputs: [],
    name: "RecipientInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "SignatureInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "SignerInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "TrustedSignatureInvalid",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newMinNonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    name: "CancelAllOrders",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "orderNonces",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    name: "CancelMultipleOrders",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "ethscriptionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    name: "EthscriptionDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "orderHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "orderNonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "ethscriptionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "endTime",
        type: "uint64",
      },
    ],
    name: "EthscriptionOrderExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "ethscriptionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    name: "EthscriptionWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint96",
        name: "creatorFeeBps",
        type: "uint96",
      },
    ],
    name: "NewCreatorFeeBps",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "currencyManager",
        type: "address",
      },
    ],
    name: "NewCurrencyManager",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint96",
        name: "protocolFeeBps",
        type: "uint96",
      },
    ],
    name: "NewProtocolFeeBps",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "protocolFeeRecipient",
        type: "address",
      },
    ],
    name: "NewProtocolFeeRecipient",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "trustedVerifier",
        type: "address",
      },
    ],
    name: "NewTrustedVerifier",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner",
    type: "event",
  },
  {
    inputs: [],
    name: "cancelAllOrders",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "orderNonces",
        type: "uint256[]",
      },
    ],
    name: "cancelMultipleMakerOrders",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "ethscriptionId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "quantity",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "startTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "protocolFeeDiscounted",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "creatorFee",
            type: "uint16",
          },
          {
            internalType: "bytes",
            name: "params",
            type: "bytes",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct OrderTypes.EthscriptionOrder",
        name: "order",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "trustedSign",
        type: "bytes",
      },
    ],
    name: "executeEthscriptionOrder",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "bytes32[]",
            name: "ethscriptionIds",
            type: "bytes32[]",
          },
          {
            internalType: "uint256[]",
            name: "quantities",
            type: "uint256[]",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "startTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "protocolFeeDiscounted",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "creatorFee",
            type: "uint16",
          },
          {
            internalType: "bytes",
            name: "params",
            type: "bytes",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct BatchOrder.EthscriptionOrder",
        name: "order",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "value",
                type: "bytes32",
              },
              {
                internalType: "enum BatchOrder.MerkleTreeNodePosition",
                name: "position",
                type: "uint8",
              },
            ],
            internalType: "struct BatchOrder.MerkleTreeNode[]",
            name: "proof",
            type: "tuple[]",
          },
        ],
        internalType: "struct BatchOrder.MerkleTree",
        name: "merkleTree",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "executeOrderWithMerkle",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "ethscriptionId",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "expiration",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "trustedSign",
        type: "bytes",
      },
    ],
    name: "withdrawEthscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "ethscriptionIds",
        type: "bytes32[]",
      },
      {
        internalType: "uint64",
        name: "expiration",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "trustedSign",
        type: "bytes",
      },
    ],
    name: "withdrawMultipleEthscriptions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEtchMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IEtchMarketInterface {
    return new utils.Interface(_abi) as IEtchMarketInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtchMarket {
    return new Contract(address, _abi, signerOrProvider) as IEtchMarket;
  }
}
