/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEthscriptionsProtocol,
  IEthscriptionsProtocolInterface,
} from "../../../contracts/interfaces/IEthscriptionsProtocol";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "initialOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "contentURI",
        type: "string",
      },
    ],
    name: "ethscriptions_protocol_CreateEthscription",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "ethscriptions_protocol_TransferEthscription",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner",
    type: "event",
  },
] as const;

export class IEthscriptionsProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): IEthscriptionsProtocolInterface {
    return new utils.Interface(_abi) as IEthscriptionsProtocolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEthscriptionsProtocol {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEthscriptionsProtocol;
  }
}
