import { categoryType } from '../marketpalce/types';
import { BasePage, IResponse } from '../types';

export type SearchType = 'token' | 'domain' | 'text' | 'number' | 'all' | '';
export interface GetOwnerRequest {
  address: string;
  category: string;
  collection: string;
  'page.size': number;
  'page.index': number;
}

export interface GetErc20ListRequest {
  status: 'All' | 'InProgress' | 'Completed' | 'New' | string;
  tokenQuery: string;
  'page.size': number;
  'page.index': number;
}

export interface GetErc20InfoRequest {
  p: string;
  tick: string;
}

export interface GetHoldersRequest {
  p: string;
  tick: string;
  ca?: string;
  'page.size': number;
  'page.index': number;
}
export interface GetTransfersRequest {
  p: string;
  tick: string;
  ca?: string;
  'page.size': number;
  'page.index': number;
}

export interface GetEthscribeRequest {
  p: string;
  tick: string;
  nonce?: number;
}

export interface GetOwnerItem {
  amount: string;
  blockTime: string;
  category: categoryType;
  chainName: string;
  collectionName: string;
  creator: string;
  ethscriptionId: string;
  ethscriptionNumber: string;
  owner: string;
  tokenId: string;
  verified: boolean;
  icon: string;
  iconContentType:
    | 'image/png'
    | 'image/jpeg'
    | 'image/png'
    | 'image/gif'
    | 'image/jpg'
    | 'image/avif'
    | 'image/webp'
    | 'image/svg+xml'
    | 'image/vnd.mozilla.apng'
    | 'image/bmp'
    | 'image/x-icon'
    | 'image/x-xpixmap'
    | 'text/html; charset=utf-8';
}

// Generated by https://quicktype.io

export interface GetErc20InfoData {
  info: GetErc20InfoItem;
}
export interface GetErc20FactoryAddressData {
  factoryAddress: string;
  registryAddress: string;
}

export interface GetErc20InfoItem {
  chainName: string;
  protocol: string;
  tick: string;
  ethscriptionId: string;
  totalSupply: string;
  minted: string;
  limitPerMint: string;
  decimal: number;
  creator: string;
  deployTime: string;
  holders: string;
  transactions: string;
  mintFormat: string;
  ethscriptionNumber: string;
  erc20s: {
    blockInterval: string;
    contractAddress: string;
    controller: string;
    deployer: string;
    factoryAddress: string;
    name: string;
    registryAddress: string;
    royalty: string;
    royaltyReceiver: string;
    startTime: string;
    symbol: string;
    walletLimit: string;
  };
}

export interface GetOwnerData {
  ethscriptions: GetOwnerItem[];
  page: BasePage;
}

export interface GetErc20Item {
  chainName: string;
  protocol: string;
  tick: string;
  deployTime: string;
  limitPerMint: string;
  totalSupply: string;
  minted: string;
  holders: string;
  minters: string;
  transactions: string;
}
export interface GetErc20ListData {
  ethscriptions: GetErc20Item[];
  page: BasePage;
}
export interface GetErc20sItem {
  chainName: string;
  protocol: string;
  tick: string;
  deployTime: string;
  limitPerMint: string;
  totalSupply: string;
  minted: string;
  holders: string;
  minters: string;
  transactions: string;
  mintFormat: string;
  ethscriptionNumber: string;
  ethscriptionId: string;
  erc20s: {
    name: string;
    symbol: string;
    contractAddress: string;
    factoryAddress: string;
    registryAddress: string;
    startTime: string;
    walletLimit: string;
    royalty: number;
  };
}
export interface GetErc20sListData {
  ethscriptions: GetErc20sItem[];
  page: BasePage;
}

export interface GetHoldersItem {
  holder: string;
  quantity: string;
  rank: number;
}
export interface GetTransfersItem {
  amount: string;
  blockNumber: string;
  blockTime: string;
  ethscriptionId: string;
  ethscriptionNumber: string;
  from: string;
  id: string;
  method: string;
  p: string;
  tick: string;
  to: string;
  txHash: string;
  txIndex: string;
}

export interface GetHoldersInfoData {
  p?: string;
  tick?: string;
  totalSupply: string;
  holders: GetHoldersItem[];
  page: BasePage;
}

export interface GetTransfersInfoData {
  transfer: GetTransfersItem[];
  page: BasePage;
}
export interface GetTokenSelectionItem {
  category: string;
  name: string;
  isBlue: boolean;
  quantity: string;
  summary: {
    chainName: string;
    protocol: string;
    tick: string;
    deployTime: string;
    limitPerMint: string;
    totalSupply: string;
    minted: string;
    holders: string;
    minters: string;
    transactions: string;
    mintFormat: string;
    ethscriptionNumber: string;
    ethscriptionId: string;
  };
}

export interface GetTokenSelectionData {
  collections: GetTokenSelectionItem[];
}

export interface GetEthscribeData {
  data: string;
}

export interface GetRecentEthsRequest {
  category: string;
  'page.size': number;
  'page.index': number;
}
export interface GetSearchedEthsRequest {
  searchType: SearchType;
  searchBy: string;
  'page.size': number;
  'page.index': number;
}

export interface GetRecentEthsItem {
  category: string;
  collectionName: string;
  ethscriptionNumber: string;
  ethscriptionId: string;
  creator: string;
  owner: string;
  blockTime: string;
  verified: boolean;
  data: string;
  mimeType: string;
  icon: string;
  confirmed: boolean;
}
export interface GetRecentTransactionItem {
  category: string;
  collectionName: string;
  ethscriptionId: string;
  ethscriptionNumber: string;
  content: string;
  event: string;
  from: string;
  to: string;
  marketplace: string;
  price: string;
  eventTime: string;
  txHash: string;
  icon: string;
}

export interface GetRecentEthsListData {
  ethscriptions: GetRecentEthsItem[];
  page: BasePage;
}
export interface GetRecentTransactionListData {
  transactions: GetRecentTransactionItem[];
  page: BasePage;
}

export interface GetTransactionStats {
  sales24h: string;
  totalSales: string;
  volume24h: string;
  totalVolume: string;
}

export interface GetRecentTransactionsRequest {
  onlySale: boolean;
  'page.size': number;
  'page.index': number;
}

export interface GetCategoryHoldersRequest {
  category: categoryType;
  collectionName: string;
  'page.size': number;
  'page.index': number;
}

// export interface GetAssetListRequest {
//   owner: string;
//   'page.size': number;
//   'page.index': number;
// }

export interface AssetItem {
  name: string;
  symbol: string;
  priceUsd: string;
  amount: string;
  valueUsd: string;
  category: 'ethereum' | 'facet';
  contractAddress: string;
  icon: string;
  decimals?: number;
  bridgedToken?: string;
}

// export interface GetAssetListData {
//   assets: AssetItem[];
//   page: {
//     size: number;
//     index: number;
//     total: number;
//   };
// }

export type GetOwnerResponse = Awaited<Readonly<IResponse<GetOwnerData>>>;
export type GetErc20ListResponse = Awaited<Readonly<IResponse<GetErc20ListData>>>;
export type GetErc20sListResponse = Awaited<Readonly<IResponse<GetErc20sListData>>>;
export type GetErc20InfoResponse = Awaited<Readonly<IResponse<GetErc20InfoData>>>;
export type getErc20FactoryAddressResponse = Awaited<Readonly<IResponse<GetErc20FactoryAddressData>>>;
export type GetOwnerInfoResponse = Awaited<Readonly<IResponse<GetHoldersInfoData>>>;
export type GetTransfersInfoResponse = Awaited<Readonly<IResponse<GetTransfersInfoData>>>;
export type GetTokenSelectonResponse = Awaited<Readonly<IResponse<GetTokenSelectionData>>>;
export type GetEthscribeDataResponse = Awaited<Readonly<IResponse<GetEthscribeData>>>;
export type GetRecentEthsListResponse = Awaited<Readonly<IResponse<GetRecentEthsListData>>>;
export type GetSearchedEthsListResponse = Awaited<Readonly<IResponse<GetRecentEthsListData>>>;
export type GetRecentTransactionListResponse = Awaited<Readonly<IResponse<GetRecentTransactionListData>>>;
export type GetTransactionStatsResponse = Awaited<Readonly<IResponse<GetTransactionStats>>>;
// export type GetAssetListResponse = Awaited<IResponse<GetAssetListData>>;
