/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace OrderTypes {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionId: PromiseOrValue<BytesLike>;
    quantity: PromiseOrValue<BigNumberish>;
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionId: string;
    quantity: BigNumber;
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export declare namespace BatchOrder {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionIds: PromiseOrValue<BytesLike>[];
    quantities: PromiseOrValue<BigNumberish>[];
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string[],
    BigNumber[],
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionIds: string[];
    quantities: BigNumber[];
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };

  export type MerkleTreeNodeStruct = {
    value: PromiseOrValue<BytesLike>;
    position: PromiseOrValue<BigNumberish>;
  };

  export type MerkleTreeNodeStructOutput = [string, number] & {
    value: string;
    position: number;
  };

  export type MerkleTreeStruct = {
    root: PromiseOrValue<BytesLike>;
    proof: BatchOrder.MerkleTreeNodeStruct[];
  };

  export type MerkleTreeStructOutput = [
    string,
    BatchOrder.MerkleTreeNodeStructOutput[]
  ] & { root: string; proof: BatchOrder.MerkleTreeNodeStructOutput[] };
}

export interface IEtchMarketInterface extends utils.Interface {
  functions: {
    "cancelAllOrders()": FunctionFragment;
    "cancelMultipleMakerOrders(uint256[])": FunctionFragment;
    "executeEthscriptionOrder((address,address,bytes32,uint256,address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),address,bytes)": FunctionFragment;
    "executeOrderWithMerkle((address,address,bytes32[],uint256[],address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),(bytes32,(bytes32,uint8)[]),address)": FunctionFragment;
    "withdrawEthscription(bytes32,uint64,bytes)": FunctionFragment;
    "withdrawMultipleEthscriptions(bytes32[],uint64,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelAllOrders"
      | "cancelMultipleMakerOrders"
      | "executeEthscriptionOrder"
      | "executeOrderWithMerkle"
      | "withdrawEthscription"
      | "withdrawMultipleEthscriptions"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelAllOrders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMultipleMakerOrders",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEthscriptionOrder",
    values: [
      OrderTypes.EthscriptionOrderStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrderWithMerkle",
    values: [
      BatchOrder.EthscriptionOrderStruct,
      BatchOrder.MerkleTreeStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthscription",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMultipleEthscriptions",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAllOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMultipleMakerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEthscriptionOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrderWithMerkle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMultipleEthscriptions",
    data: BytesLike
  ): Result;

  events: {
    "CancelAllOrders(address,uint256,uint64)": EventFragment;
    "CancelMultipleOrders(address,uint256[],uint64)": EventFragment;
    "EthscriptionDeposited(address,bytes32,uint64)": EventFragment;
    "EthscriptionOrderExecuted(bytes32,uint256,bytes32,uint256,address,address,address,uint256,uint64)": EventFragment;
    "EthscriptionWithdrawn(address,bytes32,uint64)": EventFragment;
    "NewCreatorFeeBps(uint96)": EventFragment;
    "NewCurrencyManager(address)": EventFragment;
    "NewProtocolFeeBps(uint96)": EventFragment;
    "NewProtocolFeeRecipient(address)": EventFragment;
    "NewTrustedVerifier(address)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelAllOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelMultipleOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionOrderExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCreatorFeeBps"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCurrencyManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeBps"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeRecipient"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTrustedVerifier"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface CancelAllOrdersEventObject {
  user: string;
  newMinNonce: BigNumber;
  timestamp: BigNumber;
}
export type CancelAllOrdersEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CancelAllOrdersEventObject
>;

export type CancelAllOrdersEventFilter = TypedEventFilter<CancelAllOrdersEvent>;

export interface CancelMultipleOrdersEventObject {
  user: string;
  orderNonces: BigNumber[];
  timestamp: BigNumber;
}
export type CancelMultipleOrdersEvent = TypedEvent<
  [string, BigNumber[], BigNumber],
  CancelMultipleOrdersEventObject
>;

export type CancelMultipleOrdersEventFilter =
  TypedEventFilter<CancelMultipleOrdersEvent>;

export interface EthscriptionDepositedEventObject {
  owner: string;
  ethscriptionId: string;
  timestamp: BigNumber;
}
export type EthscriptionDepositedEvent = TypedEvent<
  [string, string, BigNumber],
  EthscriptionDepositedEventObject
>;

export type EthscriptionDepositedEventFilter =
  TypedEventFilter<EthscriptionDepositedEvent>;

export interface EthscriptionOrderExecutedEventObject {
  orderHash: string;
  orderNonce: BigNumber;
  ethscriptionId: string;
  quantity: BigNumber;
  seller: string;
  buyer: string;
  currency: string;
  price: BigNumber;
  endTime: BigNumber;
}
export type EthscriptionOrderExecutedEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber
  ],
  EthscriptionOrderExecutedEventObject
>;

export type EthscriptionOrderExecutedEventFilter =
  TypedEventFilter<EthscriptionOrderExecutedEvent>;

export interface EthscriptionWithdrawnEventObject {
  owner: string;
  ethscriptionId: string;
  timestamp: BigNumber;
}
export type EthscriptionWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  EthscriptionWithdrawnEventObject
>;

export type EthscriptionWithdrawnEventFilter =
  TypedEventFilter<EthscriptionWithdrawnEvent>;

export interface NewCreatorFeeBpsEventObject {
  creatorFeeBps: BigNumber;
}
export type NewCreatorFeeBpsEvent = TypedEvent<
  [BigNumber],
  NewCreatorFeeBpsEventObject
>;

export type NewCreatorFeeBpsEventFilter =
  TypedEventFilter<NewCreatorFeeBpsEvent>;

export interface NewCurrencyManagerEventObject {
  currencyManager: string;
}
export type NewCurrencyManagerEvent = TypedEvent<
  [string],
  NewCurrencyManagerEventObject
>;

export type NewCurrencyManagerEventFilter =
  TypedEventFilter<NewCurrencyManagerEvent>;

export interface NewProtocolFeeBpsEventObject {
  protocolFeeBps: BigNumber;
}
export type NewProtocolFeeBpsEvent = TypedEvent<
  [BigNumber],
  NewProtocolFeeBpsEventObject
>;

export type NewProtocolFeeBpsEventFilter =
  TypedEventFilter<NewProtocolFeeBpsEvent>;

export interface NewProtocolFeeRecipientEventObject {
  protocolFeeRecipient: string;
}
export type NewProtocolFeeRecipientEvent = TypedEvent<
  [string],
  NewProtocolFeeRecipientEventObject
>;

export type NewProtocolFeeRecipientEventFilter =
  TypedEventFilter<NewProtocolFeeRecipientEvent>;

export interface NewTrustedVerifierEventObject {
  trustedVerifier: string;
}
export type NewTrustedVerifierEvent = TypedEvent<
  [string],
  NewTrustedVerifierEventObject
>;

export type NewTrustedVerifierEventFilter =
  TypedEventFilter<NewTrustedVerifierEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface IEtchMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEtchMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cancelAllOrders(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelMultipleMakerOrders(
    orderNonces: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeEthscriptionOrder(
    order: OrderTypes.EthscriptionOrderStruct,
    recipient: PromiseOrValue<string>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeOrderWithMerkle(
    order: BatchOrder.EthscriptionOrderStruct,
    merkleTree: BatchOrder.MerkleTreeStruct,
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawEthscription(
    ethscriptionId: PromiseOrValue<BytesLike>,
    expiration: PromiseOrValue<BigNumberish>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawMultipleEthscriptions(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    expiration: PromiseOrValue<BigNumberish>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancelAllOrders(overrides?: CallOverrides): Promise<void>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CancelAllOrders(address,uint256,uint64)"(
      user?: null,
      newMinNonce?: null,
      timestamp?: null
    ): CancelAllOrdersEventFilter;
    CancelAllOrders(
      user?: null,
      newMinNonce?: null,
      timestamp?: null
    ): CancelAllOrdersEventFilter;

    "CancelMultipleOrders(address,uint256[],uint64)"(
      user?: null,
      orderNonces?: null,
      timestamp?: null
    ): CancelMultipleOrdersEventFilter;
    CancelMultipleOrders(
      user?: null,
      orderNonces?: null,
      timestamp?: null
    ): CancelMultipleOrdersEventFilter;

    "EthscriptionDeposited(address,bytes32,uint64)"(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionDepositedEventFilter;
    EthscriptionDeposited(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionDepositedEventFilter;

    "EthscriptionOrderExecuted(bytes32,uint256,bytes32,uint256,address,address,address,uint256,uint64)"(
      orderHash?: PromiseOrValue<BytesLike> | null,
      orderNonce?: null,
      ethscriptionId?: null,
      quantity?: null,
      seller?: null,
      buyer?: null,
      currency?: null,
      price?: null,
      endTime?: null
    ): EthscriptionOrderExecutedEventFilter;
    EthscriptionOrderExecuted(
      orderHash?: PromiseOrValue<BytesLike> | null,
      orderNonce?: null,
      ethscriptionId?: null,
      quantity?: null,
      seller?: null,
      buyer?: null,
      currency?: null,
      price?: null,
      endTime?: null
    ): EthscriptionOrderExecutedEventFilter;

    "EthscriptionWithdrawn(address,bytes32,uint64)"(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionWithdrawnEventFilter;
    EthscriptionWithdrawn(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionWithdrawnEventFilter;

    "NewCreatorFeeBps(uint96)"(
      creatorFeeBps?: null
    ): NewCreatorFeeBpsEventFilter;
    NewCreatorFeeBps(creatorFeeBps?: null): NewCreatorFeeBpsEventFilter;

    "NewCurrencyManager(address)"(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;
    NewCurrencyManager(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;

    "NewProtocolFeeBps(uint96)"(
      protocolFeeBps?: null
    ): NewProtocolFeeBpsEventFilter;
    NewProtocolFeeBps(protocolFeeBps?: null): NewProtocolFeeBpsEventFilter;

    "NewProtocolFeeRecipient(address)"(
      protocolFeeRecipient?: null
    ): NewProtocolFeeRecipientEventFilter;
    NewProtocolFeeRecipient(
      protocolFeeRecipient?: null
    ): NewProtocolFeeRecipientEventFilter;

    "NewTrustedVerifier(address)"(
      trustedVerifier?: null
    ): NewTrustedVerifierEventFilter;
    NewTrustedVerifier(trustedVerifier?: null): NewTrustedVerifierEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
