/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IEthscriptionsProtocolInterface extends utils.Interface {
  functions: {};

  events: {
    "ethscriptions_protocol_CreateEthscription(address,string)": EventFragment;
    "ethscriptions_protocol_TransferEthscription(address,bytes32)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_CreateEthscription"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscription"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface ethscriptions_protocol_CreateEthscriptionEventObject {
  initialOwner: string;
  contentURI: string;
}
export type ethscriptions_protocol_CreateEthscriptionEvent = TypedEvent<
  [string, string],
  ethscriptions_protocol_CreateEthscriptionEventObject
>;

export type ethscriptions_protocol_CreateEthscriptionEventFilter =
  TypedEventFilter<ethscriptions_protocol_CreateEthscriptionEvent>;

export interface ethscriptions_protocol_TransferEthscriptionEventObject {
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionEvent = TypedEvent<
  [string, string],
  ethscriptions_protocol_TransferEthscriptionEventObject
>;

export type ethscriptions_protocol_TransferEthscriptionEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface IEthscriptionsProtocol extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEthscriptionsProtocolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ethscriptions_protocol_CreateEthscription(address,string)"(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;
    ethscriptions_protocol_CreateEthscription(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;

    "ethscriptions_protocol_TransferEthscription(address,bytes32)"(
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionEventFilter;
    ethscriptions_protocol_TransferEthscription(
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
