/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICurrencyManager } from "./ICurrencyManager";
export type { IEtchMarket } from "./IEtchMarket";
export type { IEthscriptionsProtocol } from "./IEthscriptionsProtocol";
