/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace OrderTypes {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionId: PromiseOrValue<BytesLike>;
    quantity: PromiseOrValue<BigNumberish>;
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionId: string;
    quantity: BigNumber;
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export declare namespace BatchOrder {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionIds: PromiseOrValue<BytesLike>[];
    quantities: PromiseOrValue<BigNumberish>[];
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string[],
    BigNumber[],
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionIds: string[];
    quantities: BigNumber[];
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };

  export type MerkleTreeNodeStruct = {
    value: PromiseOrValue<BytesLike>;
    position: PromiseOrValue<BigNumberish>;
  };

  export type MerkleTreeNodeStructOutput = [string, number] & {
    value: string;
    position: number;
  };

  export type MerkleTreeStruct = {
    root: PromiseOrValue<BytesLike>;
    proof: BatchOrder.MerkleTreeNodeStruct[];
  };

  export type MerkleTreeStructOutput = [
    string,
    BatchOrder.MerkleTreeNodeStructOutput[]
  ] & { root: string; proof: BatchOrder.MerkleTreeNodeStructOutput[] };
}

export interface EtchMarketInterface extends utils.Interface {
  functions: {
    "cancelAllOrders()": FunctionFragment;
    "cancelMultipleMakerOrders(uint256[])": FunctionFragment;
    "creatorFeeBps()": FunctionFragment;
    "currencyManager()": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "executeEthscriptionOrder((address,address,bytes32,uint256,address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),address,bytes)": FunctionFragment;
    "executeOrderWithMerkle((address,address,bytes32[],uint256[],address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),(bytes32,(bytes32,uint8)[]),address)": FunctionFragment;
    "hashBatchOrder(bytes32,uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "isUserOrderNonceExecutedOrCancelled(address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "protocolFeeBps()": FunctionFragment;
    "protocolFeeRecipient()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateTrustedVerifier(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "userMinOrderNonce(address)": FunctionFragment;
    "withdrawETH(address,uint256)": FunctionFragment;
    "withdrawEthscription(bytes32,uint64,bytes)": FunctionFragment;
    "withdrawMultipleEthscriptions(bytes32[],uint64,bytes)": FunctionFragment;
    "withdrawUnexpectedERC20(address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelAllOrders"
      | "cancelMultipleMakerOrders"
      | "creatorFeeBps"
      | "currencyManager"
      | "eip712Domain"
      | "executeEthscriptionOrder"
      | "executeOrderWithMerkle"
      | "hashBatchOrder"
      | "initialize"
      | "isUserOrderNonceExecutedOrCancelled"
      | "owner"
      | "pause"
      | "paused"
      | "protocolFeeBps"
      | "protocolFeeRecipient"
      | "proxiableUUID"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "updateTrustedVerifier"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "userMinOrderNonce"
      | "withdrawETH"
      | "withdrawEthscription"
      | "withdrawMultipleEthscriptions"
      | "withdrawUnexpectedERC20"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelAllOrders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMultipleMakerOrders",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currencyManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeEthscriptionOrder",
    values: [
      OrderTypes.EthscriptionOrderStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrderWithMerkle",
    values: [
      BatchOrder.EthscriptionOrderStruct,
      BatchOrder.MerkleTreeStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashBatchOrder",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTrustedVerifier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "userMinOrderNonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthscription",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMultipleEthscriptions",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnexpectedERC20",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAllOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMultipleMakerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEthscriptionOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrderWithMerkle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashBatchOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTrustedVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMinOrderNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMultipleEthscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnexpectedERC20",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "CancelAllOrders(address,uint256,uint64)": EventFragment;
    "CancelMultipleOrders(address,uint256[],uint64)": EventFragment;
    "EIP712DomainChanged()": EventFragment;
    "EthscriptionDeposited(address,bytes32,uint64)": EventFragment;
    "EthscriptionOrderExecuted(bytes32,uint256,bytes32,uint256,address,address,address,uint256,uint64)": EventFragment;
    "EthscriptionWithdrawn(address,bytes32,uint64)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NewCreatorFeeBps(uint96)": EventFragment;
    "NewCurrencyManager(address)": EventFragment;
    "NewProtocolFeeBps(uint96)": EventFragment;
    "NewProtocolFeeRecipient(address)": EventFragment;
    "NewTrustedVerifier(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelAllOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelMultipleOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionOrderExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthscriptionWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCreatorFeeBps"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCurrencyManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeBps"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeRecipient"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTrustedVerifier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface CancelAllOrdersEventObject {
  user: string;
  newMinNonce: BigNumber;
  timestamp: BigNumber;
}
export type CancelAllOrdersEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CancelAllOrdersEventObject
>;

export type CancelAllOrdersEventFilter = TypedEventFilter<CancelAllOrdersEvent>;

export interface CancelMultipleOrdersEventObject {
  user: string;
  orderNonces: BigNumber[];
  timestamp: BigNumber;
}
export type CancelMultipleOrdersEvent = TypedEvent<
  [string, BigNumber[], BigNumber],
  CancelMultipleOrdersEventObject
>;

export type CancelMultipleOrdersEventFilter =
  TypedEventFilter<CancelMultipleOrdersEvent>;

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface EthscriptionDepositedEventObject {
  owner: string;
  ethscriptionId: string;
  timestamp: BigNumber;
}
export type EthscriptionDepositedEvent = TypedEvent<
  [string, string, BigNumber],
  EthscriptionDepositedEventObject
>;

export type EthscriptionDepositedEventFilter =
  TypedEventFilter<EthscriptionDepositedEvent>;

export interface EthscriptionOrderExecutedEventObject {
  orderHash: string;
  orderNonce: BigNumber;
  ethscriptionId: string;
  quantity: BigNumber;
  seller: string;
  buyer: string;
  currency: string;
  price: BigNumber;
  endTime: BigNumber;
}
export type EthscriptionOrderExecutedEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber
  ],
  EthscriptionOrderExecutedEventObject
>;

export type EthscriptionOrderExecutedEventFilter =
  TypedEventFilter<EthscriptionOrderExecutedEvent>;

export interface EthscriptionWithdrawnEventObject {
  owner: string;
  ethscriptionId: string;
  timestamp: BigNumber;
}
export type EthscriptionWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  EthscriptionWithdrawnEventObject
>;

export type EthscriptionWithdrawnEventFilter =
  TypedEventFilter<EthscriptionWithdrawnEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NewCreatorFeeBpsEventObject {
  creatorFeeBps: BigNumber;
}
export type NewCreatorFeeBpsEvent = TypedEvent<
  [BigNumber],
  NewCreatorFeeBpsEventObject
>;

export type NewCreatorFeeBpsEventFilter =
  TypedEventFilter<NewCreatorFeeBpsEvent>;

export interface NewCurrencyManagerEventObject {
  currencyManager: string;
}
export type NewCurrencyManagerEvent = TypedEvent<
  [string],
  NewCurrencyManagerEventObject
>;

export type NewCurrencyManagerEventFilter =
  TypedEventFilter<NewCurrencyManagerEvent>;

export interface NewProtocolFeeBpsEventObject {
  protocolFeeBps: BigNumber;
}
export type NewProtocolFeeBpsEvent = TypedEvent<
  [BigNumber],
  NewProtocolFeeBpsEventObject
>;

export type NewProtocolFeeBpsEventFilter =
  TypedEventFilter<NewProtocolFeeBpsEvent>;

export interface NewProtocolFeeRecipientEventObject {
  protocolFeeRecipient: string;
}
export type NewProtocolFeeRecipientEvent = TypedEvent<
  [string],
  NewProtocolFeeRecipientEventObject
>;

export type NewProtocolFeeRecipientEventFilter =
  TypedEventFilter<NewProtocolFeeRecipientEvent>;

export interface NewTrustedVerifierEventObject {
  trustedVerifier: string;
}
export type NewTrustedVerifierEvent = TypedEvent<
  [string],
  NewTrustedVerifierEventObject
>;

export type NewTrustedVerifierEventFilter =
  TypedEventFilter<NewTrustedVerifierEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface EtchMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EtchMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creatorFeeBps(overrides?: CallOverrides): Promise<[number]>;

    currencyManager(overrides?: CallOverrides): Promise<[string]>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hashBatchOrder(
      root: PromiseOrValue<BytesLike>,
      proofLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { batchOrderHash: string }>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    protocolFeeBps(overrides?: CallOverrides): Promise<[number]>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateTrustedVerifier(
      _trustedVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawUnexpectedERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cancelAllOrders(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelMultipleMakerOrders(
    orderNonces: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creatorFeeBps(overrides?: CallOverrides): Promise<number>;

  currencyManager(overrides?: CallOverrides): Promise<string>;

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  executeEthscriptionOrder(
    order: OrderTypes.EthscriptionOrderStruct,
    recipient: PromiseOrValue<string>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeOrderWithMerkle(
    order: BatchOrder.EthscriptionOrderStruct,
    merkleTree: BatchOrder.MerkleTreeStruct,
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hashBatchOrder(
    root: PromiseOrValue<BytesLike>,
    proofLength: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isUserOrderNonceExecutedOrCancelled(
    user: PromiseOrValue<string>,
    orderNonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  protocolFeeBps(overrides?: CallOverrides): Promise<number>;

  protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateTrustedVerifier(
    _trustedVerifier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userMinOrderNonce(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawETH(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawEthscription(
    ethscriptionId: PromiseOrValue<BytesLike>,
    expiration: PromiseOrValue<BigNumberish>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawMultipleEthscriptions(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    expiration: PromiseOrValue<BigNumberish>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawUnexpectedERC20(
    token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancelAllOrders(overrides?: CallOverrides): Promise<void>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    creatorFeeBps(overrides?: CallOverrides): Promise<number>;

    currencyManager(overrides?: CallOverrides): Promise<string>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hashBatchOrder(
      root: PromiseOrValue<BytesLike>,
      proofLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    protocolFeeBps(overrides?: CallOverrides): Promise<number>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateTrustedVerifier(
      _trustedVerifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawUnexpectedERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "CancelAllOrders(address,uint256,uint64)"(
      user?: null,
      newMinNonce?: null,
      timestamp?: null
    ): CancelAllOrdersEventFilter;
    CancelAllOrders(
      user?: null,
      newMinNonce?: null,
      timestamp?: null
    ): CancelAllOrdersEventFilter;

    "CancelMultipleOrders(address,uint256[],uint64)"(
      user?: null,
      orderNonces?: null,
      timestamp?: null
    ): CancelMultipleOrdersEventFilter;
    CancelMultipleOrders(
      user?: null,
      orderNonces?: null,
      timestamp?: null
    ): CancelMultipleOrdersEventFilter;

    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "EthscriptionDeposited(address,bytes32,uint64)"(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionDepositedEventFilter;
    EthscriptionDeposited(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionDepositedEventFilter;

    "EthscriptionOrderExecuted(bytes32,uint256,bytes32,uint256,address,address,address,uint256,uint64)"(
      orderHash?: PromiseOrValue<BytesLike> | null,
      orderNonce?: null,
      ethscriptionId?: null,
      quantity?: null,
      seller?: null,
      buyer?: null,
      currency?: null,
      price?: null,
      endTime?: null
    ): EthscriptionOrderExecutedEventFilter;
    EthscriptionOrderExecuted(
      orderHash?: PromiseOrValue<BytesLike> | null,
      orderNonce?: null,
      ethscriptionId?: null,
      quantity?: null,
      seller?: null,
      buyer?: null,
      currency?: null,
      price?: null,
      endTime?: null
    ): EthscriptionOrderExecutedEventFilter;

    "EthscriptionWithdrawn(address,bytes32,uint64)"(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionWithdrawnEventFilter;
    EthscriptionWithdrawn(
      owner?: PromiseOrValue<string> | null,
      ethscriptionId?: PromiseOrValue<BytesLike> | null,
      timestamp?: null
    ): EthscriptionWithdrawnEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NewCreatorFeeBps(uint96)"(
      creatorFeeBps?: null
    ): NewCreatorFeeBpsEventFilter;
    NewCreatorFeeBps(creatorFeeBps?: null): NewCreatorFeeBpsEventFilter;

    "NewCurrencyManager(address)"(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;
    NewCurrencyManager(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;

    "NewProtocolFeeBps(uint96)"(
      protocolFeeBps?: null
    ): NewProtocolFeeBpsEventFilter;
    NewProtocolFeeBps(protocolFeeBps?: null): NewProtocolFeeBpsEventFilter;

    "NewProtocolFeeRecipient(address)"(
      protocolFeeRecipient?: null
    ): NewProtocolFeeRecipientEventFilter;
    NewProtocolFeeRecipient(
      protocolFeeRecipient?: null
    ): NewProtocolFeeRecipientEventFilter;

    "NewTrustedVerifier(address)"(
      trustedVerifier?: null
    ): NewTrustedVerifierEventFilter;
    NewTrustedVerifier(trustedVerifier?: null): NewTrustedVerifierEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creatorFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    currencyManager(overrides?: CallOverrides): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hashBatchOrder(
      root: PromiseOrValue<BytesLike>,
      proofLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateTrustedVerifier(
      _trustedVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawUnexpectedERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelAllOrders(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creatorFeeBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hashBatchOrder(
      root: PromiseOrValue<BytesLike>,
      proofLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateTrustedVerifier(
      _trustedVerifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawMultipleEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      expiration: PromiseOrValue<BigNumberish>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawUnexpectedERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
