/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EtchLaunchpadInterface extends utils.Interface {
  functions: {
    "MaxAvailable()": FunctionFragment;
    "current_index()": FunctionFragment;
    "merkleRootHash()": FunctionFragment;
    "owner()": FunctionFragment;
    "publicMaxMintPerAddress()": FunctionFragment;
    "publicMint(uint256)": FunctionFragment;
    "publicMintPrice()": FunctionFragment;
    "publicMintStartAfter()": FunctionFragment;
    "publicMinted(address)": FunctionFragment;
    "recipient()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setMerkleRootHash(bytes32)": FunctionFragment;
    "setPublicMint(uint256,uint256,uint256)": FunctionFragment;
    "setRecipient(address)": FunctionFragment;
    "setWhitelistMint(uint256,uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistMaxMintPerAddress()": FunctionFragment;
    "whitelistMint(uint256,bytes32[])": FunctionFragment;
    "whitelistMintPrice()": FunctionFragment;
    "whitelistMintStartAfter()": FunctionFragment;
    "whitelistMinted(address)": FunctionFragment;
    "withdrawERC20(address,address,uint256)": FunctionFragment;
    "withdrawETH(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MaxAvailable"
      | "current_index"
      | "merkleRootHash"
      | "owner"
      | "publicMaxMintPerAddress"
      | "publicMint"
      | "publicMintPrice"
      | "publicMintStartAfter"
      | "publicMinted"
      | "recipient"
      | "renounceOwnership"
      | "setMerkleRootHash"
      | "setPublicMint"
      | "setRecipient"
      | "setWhitelistMint"
      | "transferOwnership"
      | "whitelistMaxMintPerAddress"
      | "whitelistMint"
      | "whitelistMintPrice"
      | "whitelistMintStartAfter"
      | "whitelistMinted"
      | "withdrawERC20"
      | "withdrawETH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MaxAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "current_index",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRootHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicMaxMintPerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMint",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintStartAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMinted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "recipient", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRootHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicMint",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistMint",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMaxMintPerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMint",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMintPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMintStartAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMinted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MaxAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "current_index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleRootHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicMaxMintPerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMintStartAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRootHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublicMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMaxMintPerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMintStartAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;

  events: {
    "MerkleRootHashUpdated(bytes32)": EventFragment;
    "MintInfoUpdated(uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MerkleRootHashUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintInfoUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface MerkleRootHashUpdatedEventObject {
  rootHash: string;
}
export type MerkleRootHashUpdatedEvent = TypedEvent<
  [string],
  MerkleRootHashUpdatedEventObject
>;

export type MerkleRootHashUpdatedEventFilter =
  TypedEventFilter<MerkleRootHashUpdatedEvent>;

export interface MintInfoUpdatedEventObject {
  time: BigNumber;
  mintLimit: BigNumber;
  price: BigNumber;
}
export type MintInfoUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  MintInfoUpdatedEventObject
>;

export type MintInfoUpdatedEventFilter = TypedEventFilter<MintInfoUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface EtchLaunchpad extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EtchLaunchpadInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MaxAvailable(overrides?: CallOverrides): Promise<[BigNumber]>;

    current_index(overrides?: CallOverrides): Promise<[BigNumber]>;

    merkleRootHash(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publicMintPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recipient(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

  current_index(overrides?: CallOverrides): Promise<BigNumber>;

  merkleRootHash(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

  publicMint(
    num: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

  publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

  publicMinted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recipient(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMerkleRootHash(
    rootHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPublicMint(
    _publicMintStartAfter: PromiseOrValue<BigNumberish>,
    _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
    _publicMintPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRecipient(
    _recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWhitelistMint(
    _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
    _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
    _whitelistMintPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMint(
    num: PromiseOrValue<BigNumberish>,
    merkleProof: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMinted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawERC20(
    token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawETH(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

    current_index(overrides?: CallOverrides): Promise<BigNumber>;

    merkleRootHash(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipient(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MerkleRootHashUpdated(bytes32)"(
      rootHash?: null
    ): MerkleRootHashUpdatedEventFilter;
    MerkleRootHashUpdated(rootHash?: null): MerkleRootHashUpdatedEventFilter;

    "MintInfoUpdated(uint256,uint256,uint256)"(
      time?: null,
      mintLimit?: null,
      price?: null
    ): MintInfoUpdatedEventFilter;
    MintInfoUpdated(
      time?: null,
      mintLimit?: null,
      price?: null
    ): MintInfoUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
  };

  estimateGas: {
    MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

    current_index(overrides?: CallOverrides): Promise<BigNumber>;

    merkleRootHash(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipient(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MaxAvailable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    current_index(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    merkleRootHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMaxMintPerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publicMintPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMintStartAfter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistMaxMintPerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistMintPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMintStartAfter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
