/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EthscriptionLaunchpadInterface extends utils.Interface {
  functions: {
    "MaxAvailable()": FunctionFragment;
    "current_index()": FunctionFragment;
    "depositor()": FunctionFragment;
    "ethscriptions(uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "merkleRootHash()": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "publicMaxMintPerAddress()": FunctionFragment;
    "publicMint(uint256)": FunctionFragment;
    "publicMintPrice()": FunctionFragment;
    "publicMintStartAfter()": FunctionFragment;
    "publicMinted(address)": FunctionFragment;
    "recipient()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setDepositor(address)": FunctionFragment;
    "setMaxAvailable(uint256)": FunctionFragment;
    "setMerkleRootHash(bytes32)": FunctionFragment;
    "setPublicMint(uint256,uint256,uint256)": FunctionFragment;
    "setRecipient(address)": FunctionFragment;
    "setWhitelistMint(uint256,uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "whitelistMaxMintPerAddress()": FunctionFragment;
    "whitelistMint(uint256,bytes32[])": FunctionFragment;
    "whitelistMintPrice()": FunctionFragment;
    "whitelistMintStartAfter()": FunctionFragment;
    "whitelistMinted(address)": FunctionFragment;
    "withdrawERC20(address,address,uint256)": FunctionFragment;
    "withdrawETH(address,uint256)": FunctionFragment;
    "withdrawEthscription(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MaxAvailable"
      | "current_index"
      | "depositor"
      | "ethscriptions"
      | "initialize"
      | "merkleRootHash"
      | "owner"
      | "proxiableUUID"
      | "publicMaxMintPerAddress"
      | "publicMint"
      | "publicMintPrice"
      | "publicMintStartAfter"
      | "publicMinted"
      | "recipient"
      | "renounceOwnership"
      | "setDepositor"
      | "setMaxAvailable"
      | "setMerkleRootHash"
      | "setPublicMint"
      | "setRecipient"
      | "setWhitelistMint"
      | "transferOwnership"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "whitelistMaxMintPerAddress"
      | "whitelistMint"
      | "whitelistMintPrice"
      | "whitelistMintStartAfter"
      | "whitelistMinted"
      | "withdrawERC20"
      | "withdrawETH"
      | "withdrawEthscription"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MaxAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "current_index",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "depositor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ethscriptions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRootHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMaxMintPerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMint",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintStartAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMinted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "recipient", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAvailable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRootHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicMint",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistMint",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMaxMintPerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMint",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMintPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMintStartAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistMinted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthscription",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MaxAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "current_index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merkleRootHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMaxMintPerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMintStartAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRootHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublicMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMaxMintPerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMintStartAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthscription",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MerkleRootHashUpdated(bytes32)": EventFragment;
    "MintInfoUpdated(uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "ethscriptions_protocol_TransferEthscription(address,bytes32)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MerkleRootHashUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintInfoUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscription"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MerkleRootHashUpdatedEventObject {
  rootHash: string;
}
export type MerkleRootHashUpdatedEvent = TypedEvent<
  [string],
  MerkleRootHashUpdatedEventObject
>;

export type MerkleRootHashUpdatedEventFilter =
  TypedEventFilter<MerkleRootHashUpdatedEvent>;

export interface MintInfoUpdatedEventObject {
  time: BigNumber;
  mintLimit: BigNumber;
  price: BigNumber;
}
export type MintInfoUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  MintInfoUpdatedEventObject
>;

export type MintInfoUpdatedEventFilter = TypedEventFilter<MintInfoUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface ethscriptions_protocol_TransferEthscriptionEventObject {
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionEvent = TypedEvent<
  [string, string],
  ethscriptions_protocol_TransferEthscriptionEventObject
>;

export type ethscriptions_protocol_TransferEthscriptionEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface EthscriptionLaunchpad extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EthscriptionLaunchpadInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MaxAvailable(overrides?: CallOverrides): Promise<[BigNumber]>;

    current_index(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositor(overrides?: CallOverrides): Promise<[string]>;

    ethscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    merkleRootHash(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publicMintPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recipient(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositor(
      _depositor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxAvailable(
      _maxAvailable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<[BigNumber]>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

  current_index(overrides?: CallOverrides): Promise<BigNumber>;

  depositor(overrides?: CallOverrides): Promise<string>;

  ethscriptions(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  merkleRootHash(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

  publicMint(
    num: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

  publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

  publicMinted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recipient(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositor(
    _depositor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxAvailable(
    _maxAvailable: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMerkleRootHash(
    rootHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPublicMint(
    _publicMintStartAfter: PromiseOrValue<BigNumberish>,
    _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
    _publicMintPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRecipient(
    _recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWhitelistMint(
    _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
    _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
    _whitelistMintPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMint(
    num: PromiseOrValue<BigNumberish>,
    merkleProof: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistMinted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawERC20(
    token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawETH(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawEthscription(
    ethscriptionId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

    current_index(overrides?: CallOverrides): Promise<BigNumber>;

    depositor(overrides?: CallOverrides): Promise<string>;

    ethscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    merkleRootHash(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipient(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setDepositor(
      _depositor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxAvailable(
      _maxAvailable: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MerkleRootHashUpdated(bytes32)"(
      rootHash?: null
    ): MerkleRootHashUpdatedEventFilter;
    MerkleRootHashUpdated(rootHash?: null): MerkleRootHashUpdatedEventFilter;

    "MintInfoUpdated(uint256,uint256,uint256)"(
      time?: null,
      mintLimit?: null,
      price?: null
    ): MintInfoUpdatedEventFilter;
    MintInfoUpdated(
      time?: null,
      mintLimit?: null,
      price?: null
    ): MintInfoUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "ethscriptions_protocol_TransferEthscription(address,bytes32)"(
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionEventFilter;
    ethscriptions_protocol_TransferEthscription(
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {
    MaxAvailable(overrides?: CallOverrides): Promise<BigNumber>;

    current_index(overrides?: CallOverrides): Promise<BigNumber>;

    depositor(overrides?: CallOverrides): Promise<BigNumber>;

    ethscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    merkleRootHash(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    publicMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publicMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipient(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositor(
      _depositor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxAvailable(
      _maxAvailable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistMaxMintPerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistMintPrice(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMintStartAfter(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MaxAvailable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    current_index(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ethscriptions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    merkleRootHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMaxMintPerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicMint(
      num: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publicMintPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMintStartAfter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositor(
      _depositor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxAvailable(
      _maxAvailable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMerkleRootHash(
      rootHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPublicMint(
      _publicMintStartAfter: PromiseOrValue<BigNumberish>,
      _publicMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _publicMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRecipient(
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistMint(
      _whitelistMintStartAfter: PromiseOrValue<BigNumberish>,
      _whitelistMaxMintPerAddress: PromiseOrValue<BigNumberish>,
      _whitelistMintPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistMaxMintPerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMint(
      num: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistMintPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMintStartAfter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawERC20(
      token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawEthscription(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
