/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ERC20EthscriptionsInterface extends utils.Interface {
  functions: {
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "controller()": FunctionFragment;
    "decimals()": FunctionFragment;
    "deposit(bytes32[],address)": FunctionFragment;
    "depositTransfer(bytes32[],uint256,address)": FunctionFragment;
    "depositorOf(bytes32)": FunctionFragment;
    "ethscriptionIndex()": FunctionFragment;
    "ethscriptionSupply()": FunctionFragment;
    "inscribe(address)": FunctionFragment;
    "inscribeBlockInterval()": FunctionFragment;
    "inscribeCount(address)": FunctionFragment;
    "inscribeStartTime()": FunctionFragment;
    "lastInscribeBlock(address)": FunctionFragment;
    "limitPerMint()": FunctionFragment;
    "mint()": FunctionFragment;
    "name()": FunctionFragment;
    "protocol()": FunctionFragment;
    "split(uint256)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferController(address)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "walletLimit()": FunctionFragment;
    "withdrawEthscriptions(bytes32[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowance"
      | "approve"
      | "balanceOf"
      | "controller"
      | "decimals"
      | "deposit"
      | "depositTransfer"
      | "depositorOf"
      | "ethscriptionIndex"
      | "ethscriptionSupply"
      | "inscribe"
      | "inscribeBlockInterval"
      | "inscribeCount"
      | "inscribeStartTime"
      | "lastInscribeBlock"
      | "limitPerMint"
      | "mint"
      | "name"
      | "protocol"
      | "split"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferController"
      | "transferFrom"
      | "walletLimit"
      | "withdrawEthscriptions"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTransfer",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositorOf",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "ethscriptionIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethscriptionSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inscribe",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "inscribeBlockInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inscribeCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "inscribeStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastInscribeBlock",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "limitPerMint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mint", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "protocol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferController",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "walletLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthscriptions",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositorOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptionIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptionSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inscribeBlockInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inscribeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inscribeStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastInscribeBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "limitPerMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthscriptions",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ControllerTransferred(address,address)": EventFragment;
    "ERC20SV1Deployed(string,string,uint256,uint64,uint64,address,uint96,address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "ethscriptions_protocol_CreateEthscription(address,string)": EventFragment;
    "ethscriptions_protocol_DepositForEthscriptions(address,bytes32[])": EventFragment;
    "ethscriptions_protocol_DepositForTransferEthscriptions(address,bytes32[],uint256)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ControllerTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC20SV1Deployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_CreateEthscription"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_DepositForEthscriptions"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_DepositForTransferEthscriptions"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  value: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ControllerTransferredEventObject {
  previousController: string;
  newController: string;
}
export type ControllerTransferredEvent = TypedEvent<
  [string, string],
  ControllerTransferredEventObject
>;

export type ControllerTransferredEventFilter =
  TypedEventFilter<ControllerTransferredEvent>;

export interface ERC20SV1DeployedEventObject {
  name: string;
  symbol: string;
  walletLimit: BigNumber;
  inscribeStartTime: BigNumber;
  inscribeBlockInterval: BigNumber;
  royaltyReceiver: string;
  royaltyFraction: BigNumber;
  controller: string;
}
export type ERC20SV1DeployedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string, BigNumber, string],
  ERC20SV1DeployedEventObject
>;

export type ERC20SV1DeployedEventFilter =
  TypedEventFilter<ERC20SV1DeployedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  value: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface ethscriptions_protocol_CreateEthscriptionEventObject {
  initialOwner: string;
  contentURI: string;
}
export type ethscriptions_protocol_CreateEthscriptionEvent = TypedEvent<
  [string, string],
  ethscriptions_protocol_CreateEthscriptionEventObject
>;

export type ethscriptions_protocol_CreateEthscriptionEventFilter =
  TypedEventFilter<ethscriptions_protocol_CreateEthscriptionEvent>;

export interface ethscriptions_protocol_DepositForEthscriptionsEventObject {
  depositor: string;
  ids: string[];
}
export type ethscriptions_protocol_DepositForEthscriptionsEvent = TypedEvent<
  [string, string[]],
  ethscriptions_protocol_DepositForEthscriptionsEventObject
>;

export type ethscriptions_protocol_DepositForEthscriptionsEventFilter =
  TypedEventFilter<ethscriptions_protocol_DepositForEthscriptionsEvent>;

export interface ethscriptions_protocol_DepositForTransferEthscriptionsEventObject {
  depositor: string;
  ids: string[];
  amount: BigNumber;
}
export type ethscriptions_protocol_DepositForTransferEthscriptionsEvent =
  TypedEvent<
    [string, string[], BigNumber],
    ethscriptions_protocol_DepositForTransferEthscriptionsEventObject
  >;

export type ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter =
  TypedEventFilter<ethscriptions_protocol_DepositForTransferEthscriptionsEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface ERC20Ethscriptions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC20EthscriptionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    controller(overrides?: CallOverrides): Promise<[string]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    deposit(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositTransfer(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      amount: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    inscribeBlockInterval(overrides?: CallOverrides): Promise<[BigNumber]>;

    inscribeCount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    inscribeStartTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastInscribeBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    limitPerMint(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    protocol(overrides?: CallOverrides): Promise<[string]>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferController(
      newController: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    walletLimit(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  allowance(
    owner: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  controller(overrides?: CallOverrides): Promise<string>;

  decimals(overrides?: CallOverrides): Promise<number>;

  deposit(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositTransfer(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    amount: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositorOf(
    ethscriptionId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

  ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

  inscribe(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  inscribeBlockInterval(overrides?: CallOverrides): Promise<BigNumber>;

  inscribeCount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  inscribeStartTime(overrides?: CallOverrides): Promise<BigNumber>;

  lastInscribeBlock(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  protocol(overrides?: CallOverrides): Promise<string>;

  split(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferController(
    newController: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  walletLimit(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawEthscriptions(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<string>;

    decimals(overrides?: CallOverrides): Promise<number>;

    deposit(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositTransfer(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      amount: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    inscribeBlockInterval(overrides?: CallOverrides): Promise<BigNumber>;

    inscribeCount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inscribeStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    lastInscribeBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

    mint(overrides?: CallOverrides): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    protocol(overrides?: CallOverrides): Promise<string>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferController(
      newController: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    walletLimit(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;

    "ControllerTransferred(address,address)"(
      previousController?: PromiseOrValue<string> | null,
      newController?: PromiseOrValue<string> | null
    ): ControllerTransferredEventFilter;
    ControllerTransferred(
      previousController?: PromiseOrValue<string> | null,
      newController?: PromiseOrValue<string> | null
    ): ControllerTransferredEventFilter;

    "ERC20SV1Deployed(string,string,uint256,uint64,uint64,address,uint96,address)"(
      name?: null,
      symbol?: null,
      walletLimit?: null,
      inscribeStartTime?: null,
      inscribeBlockInterval?: null,
      royaltyReceiver?: null,
      royaltyFraction?: null,
      controller?: null
    ): ERC20SV1DeployedEventFilter;
    ERC20SV1Deployed(
      name?: null,
      symbol?: null,
      walletLimit?: null,
      inscribeStartTime?: null,
      inscribeBlockInterval?: null,
      royaltyReceiver?: null,
      royaltyFraction?: null,
      controller?: null
    ): ERC20SV1DeployedEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;

    "ethscriptions_protocol_CreateEthscription(address,string)"(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;
    ethscriptions_protocol_CreateEthscription(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;

    "ethscriptions_protocol_DepositForEthscriptions(address,bytes32[])"(
      depositor?: PromiseOrValue<string> | null,
      ids?: null
    ): ethscriptions_protocol_DepositForEthscriptionsEventFilter;
    ethscriptions_protocol_DepositForEthscriptions(
      depositor?: PromiseOrValue<string> | null,
      ids?: null
    ): ethscriptions_protocol_DepositForEthscriptionsEventFilter;

    "ethscriptions_protocol_DepositForTransferEthscriptions(address,bytes32[],uint256)"(
      depositor?: PromiseOrValue<string> | null,
      ids?: null,
      amount?: null
    ): ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter;
    ethscriptions_protocol_DepositForTransferEthscriptions(
      depositor?: PromiseOrValue<string> | null,
      ids?: null,
      amount?: null
    ): ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositTransfer(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      amount: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    inscribeBlockInterval(overrides?: CallOverrides): Promise<BigNumber>;

    inscribeCount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inscribeStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    lastInscribeBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    protocol(overrides?: CallOverrides): Promise<BigNumber>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferController(
      newController: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    walletLimit(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    controller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositTransfer(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      amount: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ethscriptionSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    inscribeBlockInterval(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inscribeCount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inscribeStartTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastInscribeBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    limitPerMint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferController(
      newController: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    walletLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
