/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ERC20SFactoryInterface extends utils.Interface {
  functions: {
    "deploy(string,string,uint256,uint256,uint256,uint64,uint64,address,uint96,address)": FunctionFragment;
    "ethscriptionNumber()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deploy" | "ethscriptionNumber"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ethscriptionNumber",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptionNumber",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ERC20SFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC20SFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      totalSupply: PromiseOrValue<BigNumberish>,
      limitPerMint: PromiseOrValue<BigNumberish>,
      walletLimit: PromiseOrValue<BigNumberish>,
      inscribeStartTime: PromiseOrValue<BigNumberish>,
      inscribeBlockInterval: PromiseOrValue<BigNumberish>,
      royaltyReceiver: PromiseOrValue<string>,
      royaltyFraction: PromiseOrValue<BigNumberish>,
      controller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ethscriptionNumber(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  deploy(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    totalSupply: PromiseOrValue<BigNumberish>,
    limitPerMint: PromiseOrValue<BigNumberish>,
    walletLimit: PromiseOrValue<BigNumberish>,
    inscribeStartTime: PromiseOrValue<BigNumberish>,
    inscribeBlockInterval: PromiseOrValue<BigNumberish>,
    royaltyReceiver: PromiseOrValue<string>,
    royaltyFraction: PromiseOrValue<BigNumberish>,
    controller: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ethscriptionNumber(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    deploy(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      totalSupply: PromiseOrValue<BigNumberish>,
      limitPerMint: PromiseOrValue<BigNumberish>,
      walletLimit: PromiseOrValue<BigNumberish>,
      inscribeStartTime: PromiseOrValue<BigNumberish>,
      inscribeBlockInterval: PromiseOrValue<BigNumberish>,
      royaltyReceiver: PromiseOrValue<string>,
      royaltyFraction: PromiseOrValue<BigNumberish>,
      controller: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    ethscriptionNumber(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    deploy(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      totalSupply: PromiseOrValue<BigNumberish>,
      limitPerMint: PromiseOrValue<BigNumberish>,
      walletLimit: PromiseOrValue<BigNumberish>,
      inscribeStartTime: PromiseOrValue<BigNumberish>,
      inscribeBlockInterval: PromiseOrValue<BigNumberish>,
      royaltyReceiver: PromiseOrValue<string>,
      royaltyFraction: PromiseOrValue<BigNumberish>,
      controller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ethscriptionNumber(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      totalSupply: PromiseOrValue<BigNumberish>,
      limitPerMint: PromiseOrValue<BigNumberish>,
      walletLimit: PromiseOrValue<BigNumberish>,
      inscribeStartTime: PromiseOrValue<BigNumberish>,
      inscribeBlockInterval: PromiseOrValue<BigNumberish>,
      royaltyReceiver: PromiseOrValue<string>,
      royaltyFraction: PromiseOrValue<BigNumberish>,
      controller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ethscriptionNumber(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
