/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IERC20SInterface extends utils.Interface {
  functions: {
    "depositorOf(bytes32)": FunctionFragment;
    "ethscriptionIndex()": FunctionFragment;
    "ethscriptionSupply()": FunctionFragment;
    "inscribe(address)": FunctionFragment;
    "limitPerMint()": FunctionFragment;
    "protocol()": FunctionFragment;
    "split(uint256)": FunctionFragment;
    "withdrawEthscriptions(bytes32[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositorOf"
      | "ethscriptionIndex"
      | "ethscriptionSupply"
      | "inscribe"
      | "limitPerMint"
      | "protocol"
      | "split"
      | "withdrawEthscriptions"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositorOf",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "ethscriptionIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethscriptionSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inscribe",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "limitPerMint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "protocol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEthscriptions",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositorOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptionIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethscriptionSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "limitPerMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEthscriptions",
    data: BytesLike
  ): Result;

  events: {
    "ethscriptions_protocol_CreateEthscription(address,string)": EventFragment;
    "ethscriptions_protocol_DepositForEthscriptions(address,bytes32[])": EventFragment;
    "ethscriptions_protocol_DepositForTransferEthscriptions(address,bytes32[],uint256)": EventFragment;
    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_CreateEthscription"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_DepositForEthscriptions"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_DepositForTransferEthscriptions"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ethscriptions_protocol_TransferEthscriptionForPreviousOwner"
  ): EventFragment;
}

export interface ethscriptions_protocol_CreateEthscriptionEventObject {
  initialOwner: string;
  contentURI: string;
}
export type ethscriptions_protocol_CreateEthscriptionEvent = TypedEvent<
  [string, string],
  ethscriptions_protocol_CreateEthscriptionEventObject
>;

export type ethscriptions_protocol_CreateEthscriptionEventFilter =
  TypedEventFilter<ethscriptions_protocol_CreateEthscriptionEvent>;

export interface ethscriptions_protocol_DepositForEthscriptionsEventObject {
  depositor: string;
  ids: string[];
}
export type ethscriptions_protocol_DepositForEthscriptionsEvent = TypedEvent<
  [string, string[]],
  ethscriptions_protocol_DepositForEthscriptionsEventObject
>;

export type ethscriptions_protocol_DepositForEthscriptionsEventFilter =
  TypedEventFilter<ethscriptions_protocol_DepositForEthscriptionsEvent>;

export interface ethscriptions_protocol_DepositForTransferEthscriptionsEventObject {
  depositor: string;
  ids: string[];
  amount: BigNumber;
}
export type ethscriptions_protocol_DepositForTransferEthscriptionsEvent =
  TypedEvent<
    [string, string[], BigNumber],
    ethscriptions_protocol_DepositForTransferEthscriptionsEventObject
  >;

export type ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter =
  TypedEventFilter<ethscriptions_protocol_DepositForTransferEthscriptionsEvent>;

export interface ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject {
  previousOwner: string;
  recipient: string;
  id: string;
}
export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent =
  TypedEvent<
    [string, string, string],
    ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventObject
  >;

export type ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter =
  TypedEventFilter<ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEvent>;

export interface IERC20S extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC20SInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    limitPerMint(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocol(overrides?: CallOverrides): Promise<[string]>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  depositorOf(
    ethscriptionId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

  ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

  inscribe(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

  protocol(overrides?: CallOverrides): Promise<string>;

  split(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawEthscriptions(
    ethscriptionIds: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

    protocol(overrides?: CallOverrides): Promise<string>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ethscriptions_protocol_CreateEthscription(address,string)"(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;
    ethscriptions_protocol_CreateEthscription(
      initialOwner?: PromiseOrValue<string> | null,
      contentURI?: null
    ): ethscriptions_protocol_CreateEthscriptionEventFilter;

    "ethscriptions_protocol_DepositForEthscriptions(address,bytes32[])"(
      depositor?: PromiseOrValue<string> | null,
      ids?: null
    ): ethscriptions_protocol_DepositForEthscriptionsEventFilter;
    ethscriptions_protocol_DepositForEthscriptions(
      depositor?: PromiseOrValue<string> | null,
      ids?: null
    ): ethscriptions_protocol_DepositForEthscriptionsEventFilter;

    "ethscriptions_protocol_DepositForTransferEthscriptions(address,bytes32[],uint256)"(
      depositor?: PromiseOrValue<string> | null,
      ids?: null,
      amount?: null
    ): ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter;
    ethscriptions_protocol_DepositForTransferEthscriptions(
      depositor?: PromiseOrValue<string> | null,
      ids?: null,
      amount?: null
    ): ethscriptions_protocol_DepositForTransferEthscriptionsEventFilter;

    "ethscriptions_protocol_TransferEthscriptionForPreviousOwner(address,address,bytes32)"(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
    ethscriptions_protocol_TransferEthscriptionForPreviousOwner(
      previousOwner?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BytesLike> | null
    ): ethscriptions_protocol_TransferEthscriptionForPreviousOwnerEventFilter;
  };

  estimateGas: {
    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<BigNumber>;

    ethscriptionSupply(overrides?: CallOverrides): Promise<BigNumber>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    limitPerMint(overrides?: CallOverrides): Promise<BigNumber>;

    protocol(overrides?: CallOverrides): Promise<BigNumber>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositorOf(
      ethscriptionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ethscriptionIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ethscriptionSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inscribe(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    limitPerMint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    split(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawEthscriptions(
      ethscriptionIds: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
