/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Ethscriptions } from "./ERC20Ethscriptions";
export type { ERC20S } from "./ERC20S";
export type { ERC20SFactory } from "./ERC20SFactory";
export type { ERC20SRegistry } from "./ERC20SRegistry";
export type { IERC20S } from "./IERC20S";
