/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Ethscriptions__factory } from "./ERC20Ethscriptions__factory";
export { ERC20S__factory } from "./ERC20S__factory";
export { ERC20SFactory__factory } from "./ERC20SFactory__factory";
export { ERC20SRegistry__factory } from "./ERC20SRegistry__factory";
export { IERC20S__factory } from "./IERC20S__factory";
