/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace OrderTypes {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionId: PromiseOrValue<BytesLike>;
    quantity: PromiseOrValue<BigNumberish>;
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionId: string;
    quantity: BigNumber;
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export declare namespace BatchOrder {
  export type EthscriptionOrderStruct = {
    signer: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    ethscriptionIds: PromiseOrValue<BytesLike>[];
    quantities: PromiseOrValue<BigNumberish>[];
    currency: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    protocolFeeDiscounted: PromiseOrValue<BigNumberish>;
    creatorFee: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type EthscriptionOrderStructOutput = [
    string,
    string,
    string[],
    BigNumber[],
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    number,
    string,
    string
  ] & {
    signer: string;
    creator: string;
    ethscriptionIds: string[];
    quantities: BigNumber[];
    currency: string;
    price: BigNumber;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    protocolFeeDiscounted: number;
    creatorFee: number;
    params: string;
    v: number;
    r: string;
    s: string;
  };

  export type MerkleTreeNodeStruct = {
    value: PromiseOrValue<BytesLike>;
    position: PromiseOrValue<BigNumberish>;
  };

  export type MerkleTreeNodeStructOutput = [string, number] & {
    value: string;
    position: number;
  };

  export type MerkleTreeStruct = {
    root: PromiseOrValue<BytesLike>;
    proof: BatchOrder.MerkleTreeNodeStruct[];
  };

  export type MerkleTreeStructOutput = [
    string,
    BatchOrder.MerkleTreeNodeStructOutput[]
  ] & { root: string; proof: BatchOrder.MerkleTreeNodeStructOutput[] };
}

export interface IEtchMarketInterface extends utils.Interface {
  functions: {
    "executeEthscriptionOrder((address,address,bytes32,uint256,address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),address,bytes)": FunctionFragment;
    "executeOrderWithMerkle((address,address,bytes32[],uint256[],address,uint256,uint256,uint64,uint64,uint16,uint16,bytes,uint8,bytes32,bytes32),(bytes32,(bytes32,uint8)[]),address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "executeEthscriptionOrder"
      | "executeOrderWithMerkle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeEthscriptionOrder",
    values: [
      OrderTypes.EthscriptionOrderStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrderWithMerkle",
    values: [
      BatchOrder.EthscriptionOrderStruct,
      BatchOrder.MerkleTreeStruct,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeEthscriptionOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrderWithMerkle",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IEtchMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEtchMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  executeEthscriptionOrder(
    order: OrderTypes.EthscriptionOrderStruct,
    recipient: PromiseOrValue<string>,
    trustedSign: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeOrderWithMerkle(
    order: BatchOrder.EthscriptionOrderStruct,
    merkleTree: BatchOrder.MerkleTreeStruct,
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeEthscriptionOrder(
      order: OrderTypes.EthscriptionOrderStruct,
      recipient: PromiseOrValue<string>,
      trustedSign: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeOrderWithMerkle(
      order: BatchOrder.EthscriptionOrderStruct,
      merkleTree: BatchOrder.MerkleTreeStruct,
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
